services:
  cooperfilme_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cooperfilme_backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=cooperfilme_db
      - DATABASE_PORT=5432
    depends_on:
      - cooperfilme_db
    networks:
      - cooperfilme_network

  cooperfilme_db:
    ports:
      - '5435:5432'
    image: postgres:latest
    container_name: cooperfilme_db
    environment:
      POSTGRES_USER: cooperfilme
      POSTGRES_PASSWORD: cooperfilme
      POSTGRES_DB: cooperfilme_svc_db
    volumes:
      - cooperfilme_data:/var/lib/postgresql/data
    networks:
      - cooperfilme_network

networks:
  cooperfilme_network:

volumes:
  cooperfilme_data:
