version: '3.8'

services:
  cooperfilme_db:
    ports:
      - '5435:5432'
    image: postgres:latest
    container_name: cooperfilme_db
    environment:
      POSTGRES_USER: cooperfilme
      POSTGRES_PASSWORD: cooperfilme
      POSTGRES_DB: cooperfilme_db
    volumes:
      - cooperfilme_data:/var/lib/postgresql/data
    networks:
      - cooperfilme_network

networks:
  cooperfilme_network:
    driver: bridge

volumes:
  cooperfilme_data:
